baseurl = "https://goodroot.ca"
languageCode = "en-us"
title = "Goodroot"
theme = "hugo-classic"
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[params]
    description = "An introduction to Goodroot."
    footer = "Be Excellent to Each Other | [Medium](https://medium.com/@GOODROOT) | [Keybase](https://keybase.io/goodroot) | public@goodroot.ca"
